sps: Fix flatten utility function to remove columns properly
OneIdentity/SafeguardPowerBI pull request #40
Opened 2023-05-31 12:36 UTC by marcellmeszaros

Scope: SafeguardSessions/modules/schema/SchemaUtils.pqm

If the connector fetched data from an SPS that contained a vault field (which basically contains additional fields) in one of its sessions, it returned an error because the flatten utility function handled such record type (not flat) fields incorrectly.

This bug has been fixed, plus it is now able to do column filtering for inner fields.

References: azure #418595

2023-05-31 14:48 UTC, davedusa requested changes
One thing we have missed related to schema handling is catching errors when applying schema to a response.

 In the current bug, the response that caused the error wasn't logged, so debugging would be a little hard.

Can you add a general error handler in `SchemaUtils.ApplySchema` to catch errors during the schema apply process, log the response and raise a new error?

But first of all, check that logging a response that includes a 500 sessions with all fields query (best would be to use 10.12.230.125) works properly? I'm writing this because in the [messages-Fri](https://dev.azure.com/1id/a1a8003e-d7eb-488b-b6b6-9f989b889636/_apis/wit/attachments/a40a90ca-c6f1-4669-80c1-122a9627868c?fileName=messages-Fri&download=true) log attached to the bug indicated that it could not write out elastic response to the message log fully. (Search for `OSError: [Errno 90] Message too long` in the log file).

2023-05-31 14:50 UTC, asulyi requested changes
I'd prefer if test were not relying on `PaddedTable.FromRecords` function.

2023-05-31 15:32 UTC, marcellmeszaros commented on SafeguardSessions/test/assets/schema/GetDataAsset.pqm
> +                    vault = [
The GetDataAsset.pqm contains a record with two fields: FakeResponse(list of records) and ExpectedData (table (will not contain a vault or vault.* columns)). Now I added a vault field to one of the records in the FakeResponse list to check if the test result will be correct.

In the TestGetDataWithActualData test, the FakeResponse record field mentioned above is used for response mocking. 

"fakeResponses = [
            #"https://dummy_url/api/audit/sessions?fields=%2A&sort=-start_time&snapshot=dummy_snapshot_id" = TestSafeguardSessions.ActualResponse
        ]"
The content of the ExpectedData record field (expected table) is used to check if the data was processed correctly by the GetData method.

I hope this is what the question was about.  😅

2023-05-31 15:37 UTC, marcellmeszaros commented on SafeguardSessions/test/Unit/schema/TestFlatten.query.pq
> +        _tableWithNull = PaddedTable.FromRecords({[text_field = null], [text_field = "text_value"]}),
ACK.

2023-06-01 07:49 UTC, szszeker reviewed
Will the error handling be implemented in this PR or a different one?

2023-06-01 07:49 UTC, szszeker commented on SafeguardSessions/modules/schema/SchemaUtils.pqm
> +                        @SchemaUtils.Flatten(Table.ToRecords(withFlattenedRecords), columnsToRemove)
Nice modification!

There is only a small thing that we need to take into account during testing/usage: on lower levels the names are detemined by https://github.com/OneIdentity/SafeguardPowerBI/blob/main/SafeguardSessions/modules/schema/SchemaUtils.pqm#LL108C21-L108C29

2023-06-01 11:36 UTC, davedusa commented
> Will the error handling be implemented in this PR or a different one?

We should add the error handling before the official v1.0.0+sps7.3.0 release, so I think it would be just additional administration.

2023-06-01 11:43 UTC, szszeker commented
> 



> > Will the error handling be implemented in this PR or a different one?
> 
> We should add the error handling before the official v1.0.0+sps7.3.0 release, so I think it would be just additional administration.

Ack.

2023-06-01 12:28 UTC, marcellmeszaros commented
> One thing we have missed related to schema handling is catching errors when applying schema to a response.
> 
> In the current bug, the response that caused the error wasn't logged, so debugging would be a little hard.
> 
> Can you add a general error handler in `SchemaUtils.ApplySchema` to catch errors during the schema apply process, log the response and raise a new error?
> 
> But first of all, check that logging a response that includes a 500 sessions with all fields query (best would be to use 10.12.230.125) works properly? I'm writing this because in the [messages-Fri](https://dev.azure.com/1id/a1a8003e-d7eb-488b-b6b6-9f989b889636/_apis/wit/attachments/a40a90ca-c6f1-4669-80c1-122a9627868c?fileName=messages-Fri&download=true) log attached to the bug indicated that it could not write out elastic response to the message log fully. (Search for `OSError: [Errno 90] Message too long` in the log file).

After a thorough review of the code, I don't think there is any need for extra error handling in SchemaUtils.ApplySchema, because in the current error it was not the schema apply that caused the problem, but a prior error in the connector in SchemaUtils.Flatten.

The error was in the code snippet below:

withFlattenedLists = SchemaUtils.FlattenLists(reducedTable, listFieldNames),
// Flatten records
recordFieldNames = SchemaUtils.FieldNamesOfType(**listOfRecords** (it should be reducedTable), Record.Type),
withFlattenedRecords = SchemaUtils.FlattenRecords(withFlattenedLists, recordFieldNames)

In the first parameter of the SchemaUtils.FieldNamesOfType function, a wrong variable was used, containing all the data of the original response. Later on, when we wanted to flatten the records in our data (withFlattenedLists), we also wanted to flatten record columns (recordFieldNames) that were not contained in our table and this caused the error.

The earlier error was apparently caused by us, but not handled, and so an unexpected error was created (it was in the log), but after correcting this, I don't currently see a scenario for the input data where we can be sure that an error will occur.

@davedusa  what do you think?

2023-06-01 12:31 UTC, szszeker commented
> > Will the error handling be implemented in this PR or a different one?
> 
> We should add the error handling before the official v1.0.0+sps7.3.0 release, so I think it would be just additional administration.
> 
> Edit: However, if it cannot be solved today and we wouldn't be able to close this PR in the current sprint, we had better to create a new PBI for the next sprint solve that in a separate PR and finish this one in the current sprint. :)

I think the error handling (if neccessary) won't be finished in the current sprint. Let's decide on the PBI in Marcell's comment.

2023-06-01 13:43 UTC, davedusa commented
> > One thing we have missed related to schema handling is catching errors when applying schema to a response.
> > In the current bug, the response that caused the error wasn't logged, so debugging would be a little hard.
> > Can you add a general error handler in `SchemaUtils.ApplySchema` to catch errors during the schema apply process, log the response and raise a new error?
> > But first of all, check that logging a response that includes a 500 sessions with all fields query (best would be to use 10.12.230.125) works properly? I'm writing this because in the [messages-Fri](https://dev.azure.com/1id/a1a8003e-d7eb-488b-b6b6-9f989b889636/_apis/wit/attachments/a40a90ca-c6f1-4669-80c1-122a9627868c?fileName=messages-Fri&download=true) log attached to the bug indicated that it could not write out elastic response to the message log fully. (Search for `OSError: [Errno 90] Message too long` in the log file).
> 
> After a thorough review of the code, I don't think there is any need for extra error handling in SchemaUtils.ApplySchema, because in the current error it was not the schema apply that caused the problem, but a prior error in the connector in SchemaUtils.Flatten.
> 
> The error was in the code snippet below:
> 
> withFlattenedLists = SchemaUtils.FlattenLists(reducedTable, listFieldNames), // Flatten records recordFieldNames = SchemaUtils.FieldNamesOfType(**listOfRecords** (it should be reducedTable), Record.Type), withFlattenedRecords = SchemaUtils.FlattenRecords(withFlattenedLists, recordFieldNames)
> 
> In the first parameter of the SchemaUtils.FieldNamesOfType function, a wrong variable was used, containing all the data of the original response. Later on, when we wanted to flatten the records in our data (withFlattenedLists), we also wanted to flatten record columns (recordFieldNames) that were not contained in our table and this caused the error.
> 
> The earlier error was apparently caused by us, but not handled, and so an unexpected error was created (it was in the log), but after correcting this, I don't currently see a scenario for the input data where we can be sure that an error will occur.
> 
> @davedusa what do you think?

I think we can never be 100% sure, that there won't be a dataset that would cause error during schema apply. I feel this is a risky part of the code and we should make sure that when the schema cannot be applied, we have an easy way to find out what caused the problem.

What would you do if an error happens at a customer during the schema apply? We have seen that NNX cannot log out the whole response, so it might be useless. If we don't have error handling with response logging in the connector, our only option would be to ask for an elastic snapshot from the customer, which might not an be an easy thing to ask for, as it contains sensitive customer data, that customer may deny share.

2023-06-02 09:27 UTC, szszeker approved these changes

2023-06-02 09:28 UTC, szszeker commented
As discussed, a new BPI will be opened for the error handling part.

2023-06-02 10:08 UTC, davedusa approved these changes

2023-06-02 10:12 UTC, asulyi approved these changes

2023-06-02 10:19 UTC, merged