sps: Fix GetDataFromResponse function meta and error handling
OneIdentity/SafeguardPowerBI pull request #49
Opened 2023-08-09 14:08 UTC by marcellmeszaros

Scope: SafeguardSessions\modules\request\ResponseHandler.pqm

Previously, when the GetDataFromResponse's inner GetRecordSafe function was recursively called, the meta from the original response input was not passed on, so when an internal field of the path was not found, the function could not pass the meta field of the original response RequestURL to the RequestErrors.NotParsableResponse.

This has been fixed, so the output of GetRecordSafe will contain the meta of the original respond. For the raised error, we will use the response value given to GetDataFromResponse because if we use the input record of GetRecordSafe, we would lose more and more of the original response during recursion because we only pass on the value of the internal field that was found.

References: azure #426661

2023-08-09 14:38 UTC, szszeker requested changes

2023-08-09 14:38 UTC, szszeker commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
> +                "Raises error if path's first field not found in response",
#Optional: first part of the path is

2023-08-09 14:38 UTC, szszeker commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
One small thing, otherwise everythings fine.

Could you change all occurrences of fake_response to fakeResponse?

2023-08-09 14:38 UTC, szszeker commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
> +                "Raises error if path's inner field not found in response",
#Optional: inner part of the path is

2023-08-09 14:56 UTC, asulyi approved these changes
I only have a small suggestion in the tests, but I'm not sure if it worth the effort.

2023-08-09 14:56 UTC, asulyi commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
> +                [Data = data, Meta = dataMeta],
I'd rather have this a proper assert function like
```suggestion
        AssertGetDataAndMeta = (
            description as text,
            expected_response_with_meta as record,
            response as record,
            path as text,
            optional separator as text
        ) =>
            let
                data = GetDataFromResponse(response, path, separator), dataMeta = Value.Metadata(data)
            in
                Fact(description, expected_response_with_meta, [Data = data, Meta = dataMeta]),
```
this.

But this wouldn't  work with error cases.

2023-08-09 15:02 UTC, asulyi commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
> +                [Data = data, Meta = dataMeta],
I meant when put in the provider.

2023-08-10 09:53 UTC, marcellmeszaros commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
> +                "Raises error if path's first field not found in response",
ACK.

2023-08-10 09:53 UTC, marcellmeszaros commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
ACK.

2023-08-10 09:54 UTC, marcellmeszaros commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
> +                "Raises error if path's inner field not found in response",
ACK.

2023-08-10 10:30 UTC, szszeker approved these changes

2023-08-10 10:33 UTC, asulyi approved these changes

2023-08-10 10:35 UTC, asulyi commented on SafeguardSessions/test/Unit/TestResponseHandler.query.pq
> +                [Data = data, Meta = dataMeta],
Nice! :1st_place_medal:

2023-08-10 10:39 UTC, davedusa approved these changes

2023-08-10 10:39 UTC, merged