sps: Add checksum handling targets to build system
OneIdentity/SafeguardPowerBI pull request #50
Opened 2023-08-11 10:40 UTC by asulyi

Scope: SafeguardSessions/Makefile

To stream line release process (and a preparation to automating it) we added new `make checksum` target, that calculates SHA256 checksums for build artifacts and report template.

Using `make verify-checksum` target can ensure these checksums are up-to-date.

2023-08-11 11:57 UTC, szszeker approved these changes

2023-08-17 06:12 UTC, davedusa approved these changes

2023-08-17 16:56 UTC, davedusa commented
I have created a PBI for minor improvements on the connector.
@asulyi Can you include the azure ID in the commit message?
It is azure #427269.

2023-08-17 18:00 UTC, davedusa requested changes
Please add the References line :slightly_smiling_face:

2023-08-18 11:08 UTC, davedusa approved these changes

2023-08-18 11:30 UTC, szszeker approved these changes

2023-08-18 11:31 UTC, merged