Update mds
OneIdentity/SafeguardPowerBI pull request #70
Opened 2023-11-21 13:39 UTC by szszeker

The mds have been updated according to the suggestions of the TC team.

- _The data import process finishes without any immediate signs of error_ section has been reworked.
- "handled by the the Power BI Connector" means the connector wraps the original error in a new error with extra details.

2023-11-22 08:40 UTC, c4tc4t commented on SafeguardSessions/TROUBLESHOOTING.md
> +- An error occurs when connecting SPS via the Power BI Service.
`to SPS`

2023-11-22 08:40 UTC, c4tc4t commented on SafeguardSessions/TROUBLESHOOTING.md
> +#### An error occurs when connecting SPS via the Power BI Service.
`to SPS`

2023-11-22 08:44 UTC, c4tc4t requested changes
Thanks for the updates! :-)
Two minor suggestions in TROUBLESHOOTING.md, otherwise looks good to me. :-)
Thank you!

2023-11-22 09:16 UTC, szszeker commented on SafeguardSessions/TROUBLESHOOTING.md
> +- An error occurs when connecting SPS via the Power BI Service.
Done!

2023-11-22 09:16 UTC, szszeker commented on SafeguardSessions/TROUBLESHOOTING.md
> +#### An error occurs when connecting SPS via the Power BI Service.
Done!

2023-11-23 08:17 UTC, davedusa approved these changes

2023-11-23 08:24 UTC, marcellmeszaros approved these changes

2023-11-23 09:24 UTC, merged