sps: Bump version to 8.0 pre-release
OneIdentity/SafeguardPowerBI pull request #77
Opened 2024-08-05 12:04 UTC by davedusa

Scope: SafeguardSessions

Bump version to pre-release.

2024-08-05 12:19 UTC, szszeker requested changes
The version here also needs an update: https://github.com/OneIdentity/SafeguardPowerBI/blob/main/SafeguardSessions/Src/SafeguardSessions.pq#L1

2024-08-05 12:30 UTC, marcellmeszaros reviewed
Aside from @szszeker comment, it looks good to me.

2024-08-05 15:05 UTC, davedusa commented
Thanks! Updated the SafeguardSessions pq file.

2024-08-06 07:26 UTC, marcellmeszaros approved these changes

2024-08-06 07:53 UTC, szszeker approved these changes

2024-08-06 07:54 UTC, merged